allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies: []
proxy-groups:
- name: Free_VPN_Aggregator [ALL_CONFIGS]
  proxies:
  - DIRECT
  type: select
rules:
- MATCH,Free_VPN_Aggregator [ALL_CONFIGS]
socks-port: 7891
