allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: grpc
  port: 443
  reality-opts:
    public-key: S05RWQUVH-p3uqekd0iRpIeH__NpCt0XEN2xCiQJs3Y
    short-id: c56c3ba3b9f676c5
  server: 95.85.233.181
  servername: c.primarymaster.online
  tls: true
  type: vless
  uuid: e0bb3250-1873-4b9d-b9b5-7aa6c863885f
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_CZECHIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_CZECHIA]
socks-port: 7891
