allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🇰🇷 GhostVPN
  network: tcp
  port: 8888
  server: 146.56.112.110
  servername: 146.56.112.110
  tls: false
  type: vmess
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SOUTH_KOREA]
  proxies:
  - 🇰🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SOUTH_KOREA]
socks-port: 7891
