allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: lQ8pnlOU0kqS77TA7Fftl8nSzktXLzFpOLGqCZEAhjg
    short-id: aaec521b22bbe6cb
  server: 185.221.163.211
  servername: fin1.panel11.ru
  tls: true
  type: vless
  uuid: 7957928d-bcfb-45bb-8e78-a072ef578ae4
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BRITISH_VIRGIN_ISLANDS]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BRITISH_VIRGIN_ISLANDS]
socks-port: 7891
