allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: em5MbaJeZoe--syIy7L8MEoNBwN1mLB2ur_YAY8PuQ0
    short-id: daf012feff3b00d0
  server: 2.24.131.46
  servername: www.cloudflare.com
  tls: true
  type: vless
  uuid: 5e127068-e5d0-4c3f-86c4-dfb6b34e64a4
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
  proxies:
  - 🇬🇧 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
socks-port: 7891
