allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #100'
  network: tcp
  port: 443
  reality-opts:
    public-key: zii4nGNapnFKL6SN8GzWNqFlElBvUCUFUThEP0kFH04
    short-id: c6ef72e4635d15a5
  server: 45.196.201.83
  servername: storage.yandex.net
  tls: true
  type: vless
  uuid: f75814f6-8f81-4847-b792-168c41f2dc85
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SEYCHELLES]
  proxies:
  - '🏳️ Gh0st #100'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SEYCHELLES]
socks-port: 7891
