allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: 🇪🇸 GhostVPN
  password: TCJYBIHsSW5RwR9Db8EX0A
  port: 443
  server: 68.221.254.87
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇪🇸 GhostVPN
  password: WSyL4XTwNsdv
  port: 8388
  server: 108.181.121.226
  type: ss
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SPAIN]
  proxies:
  - 🇪🇸 GhostVPN
  - 🇪🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SPAIN]
socks-port: 7891
