allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 191.215.37.90
  servername: 191.215.37.90
  tls: false
  type: vless
  uuid: SoonTeam
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_LITHUANIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_LITHUANIA]
socks-port: 7891
