allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇬🇧 GhostVPN
  network: ws
  port: 8443
  reality-opts: {}
  server: 50.7.197.2
  servername: apkav-6.bosx.net
  tls: true
  type: vless
  uuid: e83af88a-a884-48ba-b462-a1edccff15e7
  ws-opts:
    path: /api/connect
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
  proxies:
  - 🇬🇧 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
socks-port: 7891
