allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🇦🇪 GhostVPN
  network: tcp
  port: 1233
  server: 195.133.192.232
  servername: gb.uniquenames.net
  tls: true
  type: vmess
  uuid: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_ARAB_EMIRATES]
  proxies:
  - 🇦🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_ARAB_EMIRATES]
socks-port: 7891
