allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: oOp4xgD1R9MGm17qYp4XIHiq1dAfTaknr39UvhOv8Gc
    short-id: ab55ed2e71e8f58e
  server: 217.12.194.226
  servername: www.cloudflare.com
  tls: true
  type: vless
  uuid: b8cff836-8a21-4b72-a77d-231c8678c711
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_GREECE]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_GREECE]
socks-port: 7891
