allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇮 GhostVPN
  network: xhttp
  port: 2083
  reality-opts:
    public-key: zq3gOJkXi6laNuxMohL3lr-wFOKi4Z9oG7QuMMiTDAk
    short-id: 29b21343ab4d
  server: 31.76.80.69
  servername: www.amd.com
  tls: true
  type: vless
  uuid: 8975546a-375c-4966-8064-19fc0f66f30a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_FINLAND]
  proxies:
  - 🇫🇮 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_FINLAND]
socks-port: 7891
