allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #67'
  network: tcp
  port: 443
  reality-opts:
    public-key: LaGTRJ1CJnnYV7FnyqQnU28I0xFTPFKI8xmUFwig5ic
    short-id: c410508e9721512b
  server: 152.53.46.27
  servername: stackoverflow.com
  tls: true
  type: vless
  uuid: bcc094e4-1a85-8a25-f8e1-5b08b9af841c
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_AUSTRIA]
  proxies:
  - '🏳️ Gh0st #67'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_AUSTRIA]
socks-port: 7891
