allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: ws
  port: 80
  reality-opts: {}
  server: 103.86.49.57
  servername: 103.86.49.57
  tls: false
  type: vless
  uuid: 3c52e091-6714-4915-949f-2149fe69951b
  ws-opts:
    path: /ws
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_THAILAND]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_THAILAND]
socks-port: 7891
