allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 1xxZM10W-A8nuj6MOXFd1kA9lS7bEy-5SO5j-jrd_Cg
    short-id: b70076439f4a1340
  server: 82.117.255.87
  servername: www.cloudflare.com
  tls: true
  type: vless
  uuid: b748a230-b157-4401-8423-f8e44df31b5e
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ROMANIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ROMANIA]
socks-port: 7891
