allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇺🇸 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: cNWgfJHerzIEb0RXxncP8R9Ex8-FkALOtbhneEIHpR0
    short-id: a1b2c4d4a1b2c5d5
  server: 31.76.22.141
  servername: www.sciencedirect.com
  tls: true
  type: vless
  uuid: 9500cf8b-020a-4a70-906c-e14bb5375875
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_STATES]
  proxies:
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_STATES]
socks-port: 7891
