allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #8'
  network: tcp
  port: 13443
  reality-opts:
    public-key: gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM
    short-id: a7f3c91b2e6d84c0
  server: 195.123.208.92
  servername: auto.cendora.ru
  tls: true
  type: vless
  uuid: fc1b3bda-b226-452a-8c5c-b0e36a1f8f88
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_LATVIA]
  proxies:
  - '🏳️ Gh0st #8'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_LATVIA]
socks-port: 7891
