allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 6HRVYg1i4ah9VhuV5hne2-JA8Z5HTV5jbFi-h3qKsDQ
    short-id: dd4d615422c6424c
  server: 109.104.106.135
  servername: d2-ro.cloud-cdn.xyz
  tls: true
  type: vless
  uuid: 36a9a243-84aa-4bbf-8a1d-fc4739795d46
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ROMANIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ROMANIA]
socks-port: 7891
