allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇳🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: qY222OdlPFi9DvfoHZNgp0UHLubudtKLLF_KMuDy-Ho
    short-id: 9795f83547c168d3
  server: 89.23.103.121
  servername: www.debian.org
  tls: true
  type: vless
  uuid: 7596b721-f311-4194-96e6-b7b407cd6083
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_THE_NETHERLANDS]
  proxies:
  - 🇳🇱 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_THE_NETHERLANDS]
socks-port: 7891
