allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  password: UO36402987
  port: 443
  server: 34.251.228.118
  skip-cert-verify: true
  sni: definite-ladybird.rooster465.autos
  type: trojan
- name: 🏳️ GhostVPN
  password: ND91608427
  port: 443
  server: 54.217.133.71
  skip-cert-verify: true
  sni: willing-beagle.rooster465.autos
  type: trojan
- name: 🏳️ GhostVPN
  password: UO36402987
  port: 443
  server: 54.216.124.178
  skip-cert-verify: true
  sni: warm-bass.rooster465.autos
  type: trojan
- name: 🏳️ GhostVPN
  password: ND91608427
  port: 443
  server: 54.170.212.206
  skip-cert-verify: true
  sni: skilled-lioness.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_IRELAND]
  proxies:
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_IRELAND]
socks-port: 7891
