allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ Belgium 15
  network: tcp
  port: 443
  reality-opts:
    public-key: cv_KJnMzQUZruACPbH-BCgLWrYqPm2dbUymg-gW_sVc
    short-id: ''
  server: 109.69.218.167
  servername: agile-raptor.cdn.cachefleet.com
  tls: true
  type: vless
  uuid: 5117ad77-cd9a-46e9-995b-b601b0b5e435
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BELGIUM]
  proxies:
  - 🏳️ Belgium 15
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BELGIUM]
socks-port: 7891
