allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇭🇰 GhostVPN
  password: BxceQaOe
  port: 26704
  server: 95.40.205.94
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_HONG_KONG]
  proxies:
  - 🇭🇰 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_HONG_KONG]
socks-port: 7891
