allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇮🇳 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE
    short-id: ff776ff77be48b88
  server: 217.216.79.6
  servername: ind2.helper-internet.com
  tls: true
  type: vless
  uuid: 670decfe-68cc-499e-8cb1-22b39c20acbb
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_INDIA]
  proxies:
  - 🇮🇳 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_INDIA]
socks-port: 7891
