allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 47424
  reality-opts: {}
  server: 46.8.228.91
  servername: 46.8.228.91
  tls: false
  type: vless
  uuid: 6de486c1-dbad-4540-8875-98c35e9cd173
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_LATVIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_LATVIA]
socks-port: 7891
