allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 8hse7wRRL-F66rQ-aAeetKTw0MSeJC7Rr6EaDeLzdCU
    short-id: ''
  server: 109.69.218.207
  servername: crisp-titan.cdn.cachefleet.com
  tls: true
  type: vless
  uuid: 2a12bb81-f3a3-41bb-99ab-36febf676b4a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BELGIUM]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BELGIUM]
socks-port: 7891
