allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: 🇪🇸 GhostVPN
  password: WSyL4XTwNsdv
  port: 8388
  server: 108.181.121.226
  type: ss
- name: 🇪🇸 GhostVPN
  password: 2eutknankxtbgkwcajzt
  port: 52794
  server: 193.148.19.210
  skip-cert-verify: true
  sni: www.vk.com
  type: trojan
- name: 🇪🇸 GhostVPN
  password: 2eutknankxtbgkwcajzt
  port: 52794
  server: 193.148.19.213
  skip-cert-verify: true
  sni: 193.148.19.213
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SPAIN]
  proxies:
  - 🇪🇸 GhostVPN
  - 🇪🇸 GhostVPN
  - 🇪🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SPAIN]
socks-port: 7891
