allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: xhttp
  port: 443
  reality-opts: {}
  server: 185.136.12.179
  servername: deu683.lackerdeu.org
  tls: true
  type: vless
  uuid: 2cca8201-c93e-40eb-bd8a-fea4170c169e
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_KAZAKHSTAN]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_KAZAKHSTAN]
socks-port: 7891
