allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🏳️ Kazakhstan 56
  network: ws
  port: 80
  server: 38.107.234.57
  servername: 38.107.234.57
  tls: false
  type: vmess
  uuid: 567f4be5-12ab-42e1-b8d9-db6fd1fdd31c
  ws-opts:
    headers:
      Host: 3h-kazakhstan1.09vpn.com
    path: /vmess/
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_KAZAKHSTAN]
  proxies:
  - 🏳️ Kazakhstan 56
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_KAZAKHSTAN]
socks-port: 7891
