allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 32355
  reality-opts: {}
  server: 103.227.225.198
  servername: 103.227.225.198
  tls: false
  type: vless
  uuid: a2f6da81-64bd-4b86-b806-5658e161b7e4
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_TAIWAN]
  proxies:
  - 🇹🇼 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_TAIWAN]
socks-port: 7891
