allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇺🇸 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w
    short-id: 00a61d55a07de885
  server: 5.34.179.185
  servername: us.convert-flow.net
  tls: true
  type: vless
  uuid: 5710bc50-f5ff-0348-a3f5-067959ed2644
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w
    short-id: 00a61d55a07de885
  server: 5.34.179.183
  servername: us.convert-flow.net
  tls: true
  type: vless
  uuid: 5710bc50-f5ff-0348-a3f5-067959ed2644
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_STATES]
  proxies:
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_STATES]
socks-port: 7891
