allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🏳️ GhostVPN
  network: ws
  port: 53548
  server: 202.47.89.133
  servername: 202.47.89.133
  tls: false
  type: vmess
  uuid: 3a03613b-bbac-4a22-bee6-2c9a751a2761
  ws-opts:
    headers:
      Host: ''
    path: /dkfjh222
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_INDONESIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_INDONESIA]
socks-port: 7891
