allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇮🇳 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: Gy6W0bXf2bpxoG1k3szp8X0ekzoyXlEtzT8V4mYQ3EE
    short-id: 29fe4205ddc971a8
  server: 194.61.31.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 0bf89828-484f-4710-9581-12aa961e3bf1
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_INDIA]
  proxies:
  - 🇮🇳 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_INDIA]
socks-port: 7891
