allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇧🇷 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: yg6IqqBKuUew1C26U8I2ZiQuBXLcGSKN3MyxEzhsaFM
    short-id: b6ff5a25b94803d8
  server: 147.45.116.30
  servername: br-storage10.infrastucture.site
  tls: true
  type: vless
  uuid: eac6ea16-8963-4948-8ba8-0dd3bab4773e
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BRAZIL]
  proxies:
  - 🇧🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BRAZIL]
socks-port: 7891
