allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #10'
  network: tcp
  port: 40443
  reality-opts:
    public-key: MN6QjUHDUXyteMdR-cDna89fq4X3qgQhLnNqTtRUbBQ
    short-id: a8ae
  server: 194.76.154.31
  servername: deepl.com
  tls: true
  type: vless
  uuid: 9f0baff8-bdee-4de9-9515-bcc4932b41fa
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_CYPRUS]
  proxies:
  - '🏳️ Gh0st #10'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_CYPRUS]
socks-port: 7891
