allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 32396
  reality-opts:
    public-key: Pj1XWo01sxdH8jKJ_8DoJiZDFANHFKRAqOncP8RNkwU
    short-id: dd6ce6af95001a
  server: 172.232.196.241
  servername: www.sony.com
  tls: true
  type: vless
  uuid: bd6ebd72-25cd-4209-a418-a8c72946da90
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ITALY]
  proxies:
  - 🇮🇹 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ITALY]
socks-port: 7891
