allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇳🇱 GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 158.178.147.174
  servername: 158.178.147.174
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🇳🇱 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 51.15.57.139
  servername: 51.15.57.139
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇳🇱 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 51.15.56.211
  servername: 51.15.56.211
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_THE_NETHERLANDS]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_THE_NETHERLANDS]
socks-port: 7891
