allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇷🇺 GhostVPN
  network: tcp
  port: 8443
  reality-opts: {}
  server: 89.19.223.163
  servername: 89.19.223.163
  tls: false
  type: vless
  uuid: 62d41535-25d3-4bb6-8378-e918cfeba95f
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: tcp
  port: 8443
  reality-opts: {}
  server: 89.19.223.137
  servername: 89.19.223.137
  tls: false
  type: vless
  uuid: 62d41535-25d3-4bb6-8378-e918cfeba95f
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_RUSSIA]
  proxies:
  - 🇷🇺 GhostVPN
  - 🇷🇺 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_RUSSIA]
socks-port: 7891
