allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #90'
  network: tcp
  port: 443
  reality-opts:
    public-key: eaRNeC8fccrx0nBNvBpAXZgK4m4FxfnQ-t0W7NOM7mU
    short-id: e53048e82bb20077
  server: 185.159.73.247
  servername: asia.cendora.ru
  tls: true
  type: vless
  uuid: fc1b3bda-b226-452a-8c5c-b0e36a1f8f88
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ISRAEL]
  proxies:
  - '🏳️ Gh0st #90'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ISRAEL]
socks-port: 7891
