allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇹🇷 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: G_LkIUtwCR5RoHxB021-jY8DlwXwKKKgFOes8p54XU0
    short-id: 40c3a20ae97f78a0
  server: 45.136.5.49
  servername: turkey.anonch.net
  tls: true
  type: vless
  uuid: d16a7171-625d-4d09-9459-859f1c9b3b0a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_TÜRKIYE]
  proxies:
  - 🇹🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_TÜRKIYE]
socks-port: 7891
