allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 158.247.126.16
  servername: 158.247.126.16
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.221.79
  servername: 157.137.221.79
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 149.130.168.29
  servername: 149.130.168.29
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 149.130.188.226
  servername: 149.130.188.226
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_COLOMBIA]
  proxies:
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_COLOMBIA]
socks-port: 7891
