allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇮 GhostVPN
  network: tcp
  port: 26795
  reality-opts: {}
  server: 65.109.208.236
  servername: 65.109.208.236
  tls: false
  type: vless
  uuid: c896406b-ccc4-4c37-8b8c-15964f32a9a2
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_FINLAND]
  proxies:
  - 🇫🇮 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_FINLAND]
socks-port: 7891
