allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇸🇬 GhostVPN
  network: ws
  port: 443
  reality-opts: {}
  server: 52.74.176.20
  servername: 52.74.176.20
  tls: false
  type: vless
  uuid: 5ad0bed3-68ac-495e-b778-8b2d0e1dc176
  ws-opts:
    path: ''
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SINGAPORE]
  proxies:
  - 🇸🇬 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SINGAPORE]
socks-port: 7891
