allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇧🇷 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 201.24.49.120
  servername: 201.24.49.120
  tls: false
  type: vless
  uuid: b671573f-6303-4cdf-ad50-0401d07e85bf
  ws-opts:
    path: /v1
- name: 🇧🇷 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.24.49.120
  servername: 201.24.49.120
  tls: false
  type: vless
  uuid: 714e1212-6707-471e-9f40-2fbd3d8d3b4b
  ws-opts:
    path: /v1
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BRAZIL]
  proxies:
  - 🇧🇷 GhostVPN
  - 🇧🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BRAZIL]
socks-port: 7891
