allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇦🇪 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 7vBIjExxrcwTpbknJXdAfpTjddGw8AGww0izaZUU528
    short-id: 313328a7aa886b12
  server: 151.242.160.15
  servername: edge-de2.mystatic-cdn.ru
  tls: true
  type: vless
  uuid: b11841e3-2acc-45ff-afe0-a9ed9a823aaa
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_ARAB_EMIRATES]
  proxies:
  - 🇦🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_ARAB_EMIRATES]
socks-port: 7891
