allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: ''
  name: '🇹🇼 Gh0st #88'
  network: tcp
  port: 35034
  server: 165.154.195.38
  servername: 165.154.195.38
  tls: false
  type: vmess
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_TAIWAN]
  proxies:
  - '🇹🇼 Gh0st #88'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_TAIWAN]
socks-port: 7891
