allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🇨🇦 Gh0st #45'
  network: xhttp
  port: 2087
  reality-opts: {}
  server: 74.49.214.21
  servername: ch-de.sdcards.ir
  tls: true
  type: vless
  uuid: 9d6104a5-fc6d-4fe6-95b7-80d8f699e09d
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_CANADA]
  proxies:
  - '🇨🇦 Gh0st #45'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_CANADA]
socks-port: 7891
