allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: '🇰🇷 Gh0st #94'
  network: tcp
  port: 443
  server: 140.238.2.250
  servername: 140.238.2.250
  tls: false
  type: vmess
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SOUTH_KOREA]
  proxies:
  - '🇰🇷 Gh0st #94'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SOUTH_KOREA]
socks-port: 7891
