allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 16865
  reality-opts: {}
  server: 136.0.110.35
  servername: 136.0.110.35
  tls: true
  type: vless
  uuid: 08d4e275-eb67-4878-949c-79a39e10cca1
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_MALAYSIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_MALAYSIA]
socks-port: 7891
