allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇷 GhostVPN
  password: QV31589740
  port: 443
  server: 51.44.160.58
  skip-cert-verify: true
  sni: great-krill.rooster465.autos
  type: trojan
- name: 🇫🇷 GhostVPN
  password: ND91608427
  port: 443
  server: 13.36.175.151
  skip-cert-verify: true
  sni: classic-gator.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_FRANCE]
  proxies:
  - 🇫🇷 GhostVPN
  - 🇫🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_FRANCE]
socks-port: 7891
