allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: tszWkJf8EdAkXhxvD-T_xA08SjU_x7lf15lXrPCLVn8
    short-id: 3c88b649989ffa95
  server: 188.255.163.44
  servername: www.ya.ru
  tls: true
  type: vless
  uuid: acc50200-7f21-4f90-9cca-0057efcbf042
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_POLAND]
  proxies:
  - 🇵🇱 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_POLAND]
socks-port: 7891
