allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ Malaysia 18
  network: xhttp
  port: 443
  reality-opts: {}
  server: 47.250.212.59
  servername: de.lezzatzone.ir
  tls: true
  type: vless
  uuid: 406d8436-0eb9-4eb2-84fb-960e076ffba6
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_MALAYSIA]
  proxies:
  - 🏳️ Malaysia 18
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_MALAYSIA]
socks-port: 7891
