allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇭🇰 GhostVPN
  password: d1960ba9f0f6353353994fa844cf817b
  port: 6357
  server: 18.163.180.201
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_HONG_KONG]
  proxies:
  - 🇭🇰 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_HONG_KONG]
socks-port: 7891
