allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇨🇭 GhostVPN
  network: ws
  port: 8204
  reality-opts: {}
  server: 92.119.165.177
  servername: zeta.optiklink.com
  tls: true
  type: vless
  uuid: ed1aaa45-18b3-4c07-a434-ea42e2dfba77
  ws-opts:
    path: /gayporn---gayporn---gayporn---gayporn---gayporn---gayporn---gayporn
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SWITZERLAND]
  proxies:
  - 🇨🇭 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SWITZERLAND]
socks-port: 7891
