allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: xhttp
  port: 443
  reality-opts:
    public-key: sJTPQLMDCyPAbRcaJM-P8Y3_xRVpEEGrvv-kkIuIuQE
    short-id: ''
  server: 194.33.61.19
  servername: www.google.com
  tls: true
  type: vless
  uuid: 3548fba9-e70a-4fe3-98f0-ff7e392226f4
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SEYCHELLES]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SEYCHELLES]
socks-port: 7891
