allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 5GhMSJXQv1wXHVD999YHRRj83m-7VKH8qb_vTxBGbng
    short-id: 08
  server: 77.73.131.154
  servername: vindobona.org
  tls: true
  type: vless
  uuid: 1f4c983e-382c-d2fa-b2dc-7981f02b34de
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_AUSTRIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_AUSTRIA]
socks-port: 7891
