allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 8443
  reality-opts: {}
  server: 87.121.218.169
  servername: 87.121.218.169
  tls: true
  type: vless
  uuid: 9e1e2fad-b6ca-474b-a28d-4b52c7891da0
  ws-opts: {}
- name: 🏳️ GhostVPN
  password: bptHV5U91mWneB61rRKhCQ8f
  port: 443
  server: 87.121.218.169
  skip-cert-verify: true
  sni: 87.121.218.169
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BULGARIA]
  proxies:
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BULGARIA]
socks-port: 7891
