allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🇮🇷 GhostVPN
  network: ws
  port: 443
  server: 185.59.113.4
  servername: 185.59.113.4
  tls: false
  type: vmess
  uuid: efc02ac5-685e-4c88-b3da-ce3dfc236585
  ws-opts:
    headers:
      Host: amir.amirport.ir
    path: /
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_IRAN]
  proxies:
  - 🇮🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_IRAN]
socks-port: 7891
