allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #34'
  network: tcp
  port: 20342
  reality-opts: {}
  server: 141.133.172.222
  servername: 141.133.172.222
  tls: false
  type: vless
  uuid: 5eecb34f-c905-4c77-b7fb-d830b451cd11
  ws-opts: {}
- name: '🏳️ Gh0st #66'
  network: tcp
  port: 443
  reality-opts:
    public-key: b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI
    short-id: 00bca5982f82d083
  server: 46.8.113.190
  servername: eu-central.cendora.ru
  tls: true
  type: vless
  uuid: fc1b3bda-b226-452a-8c5c-b0e36a1f8f88
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_CZECHIA]
  proxies:
  - '🏳️ Gh0st #34'
  - '🏳️ Gh0st #66'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_CZECHIA]
socks-port: 7891
