allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 8443
  reality-opts:
    public-key: vSwth-8n5PZiAc27bkA_6qlxhuPOC0uBft7F2DWrPXs
    short-id: 5ecd85141e301108
  server: 202.165.67.16
  servername: mila.4ch.pro
  tls: true
  type: vless
  uuid: d53f098c-c146-4c16-b8fc-263743fdb6b3
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ITALY]
  proxies:
  - 🇮🇹 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ITALY]
socks-port: 7891
