allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.210.130
  servername: 157.137.210.130
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 149.130.177.227
  servername: 149.130.177.227
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 149.130.178.238
  servername: 149.130.178.238
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 149.130.191.17
  servername: 149.130.191.17
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.226.194
  servername: 157.137.226.194
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.229.190
  servername: 157.137.229.190
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.221.5
  servername: 157.137.221.5
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_COLOMBIA]
  proxies:
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_COLOMBIA]
socks-port: 7891
