allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇸🇪 GhostVPN
  network: tcp
  port: 5015
  reality-opts:
    public-key: HNjZe5pYUhcuE8sASYVVrVSMW_jFfekgLnrnO4xXIyQ
    short-id: a1b2c3d4
  server: 31.207.7.106
  servername: fi.aeternavpn.space
  tls: true
  type: vless
  uuid: 1206bad5-dcc9-410e-9595-d9fe9ee54085
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 4sJi_kuLKl7--j0yDT5feC-pAQUAOInTZh4mOVlP11E
    short-id: 2c9ee5b9f7255849
  server: 46.246.90.11
  servername: dl.google.com
  tls: true
  type: vless
  uuid: 716576a9-7575-44f0-a82a-a21f774861f5
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SWEDEN]
  proxies:
  - 🇸🇪 GhostVPN
  - 🇸🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SWEDEN]
socks-port: 7891
