allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇷 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: lRuJPDrUb0b32-47hl4BgDoQutqmkuW31N4qVxbDgmI
    short-id: dc927a04e8572c61
  server: 195.58.140.146
  servername: d1-fr.cloud-cdn.xyz
  tls: true
  type: vless
  uuid: d7790b85-9659-4558-a405-e0ab57d32984
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_FRANCE]
  proxies:
  - 🇫🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_FRANCE]
socks-port: 7891
