allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🇪🇸 Gh0st #60'
  password: 2eutknankxtbgkwcajzt
  port: 52794
  server: 193.148.19.213
  skip-cert-verify: true
  sni: 193.148.19.213
  type: trojan
- name: '🇪🇸 Gh0st #61'
  password: 2eutknankxtbgkwcajzt
  port: 52794
  server: 193.148.19.210
  skip-cert-verify: true
  sni: www.vk.com
  type: trojan
- name: '🇪🇸 Gh0st #62'
  network: ws
  port: 25198
  reality-opts: {}
  server: 5.180.173.248
  servername: 5.180.173.248
  tls: false
  type: vless
  uuid: deb9c015-1ffe-4e41-9d21-310eb0422a4c
  ws-opts:
    path: /xray
- name: '🇪🇸 Gh0st #87'
  network: tcp
  port: 443
  reality-opts:
    public-key: m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0
    short-id: dd3ff38418d29d22
  server: 113.30.149.20
  servername: eu-west.cendora.ru
  tls: true
  type: vless
  uuid: fc1b3bda-b226-452a-8c5c-b0e36a1f8f88
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SPAIN]
  proxies:
  - '🇪🇸 Gh0st #60'
  - '🇪🇸 Gh0st #61'
  - '🇪🇸 Gh0st #62'
  - '🇪🇸 Gh0st #87'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SPAIN]
socks-port: 7891
