allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: ws
  port: 443
  reality-opts: {}
  server: 195.123.226.21
  servername: 195.123.226.21
  tls: false
  type: vless
  uuid: 33851d53-ede0-45f7-9eb8-9aa961f7d200
  ws-opts:
    path: /vless
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BULGARIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BULGARIA]
socks-port: 7891
