allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #63'
  network: xhttp
  port: 8443
  reality-opts: {}
  server: 104.26.14.137
  servername: sa.sorixset.ir
  tls: true
  type: vless
  uuid: 00328cdc-2250-4da8-bf32-1ce54f1b8ca8
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNKNOWN]
  proxies:
  - '🏳️ Gh0st #63'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNKNOWN]
socks-port: 7891
