allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 2443
  reality-opts: {}
  server: 84.32.110.58
  servername: lao10.enterquality.online
  tls: true
  type: vless
  uuid: cfae13ae-5f59-42dc-a6cd-a2736dd9dca9
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_LITHUANIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_LITHUANIA]
socks-port: 7891
