allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇷🇺 GhostVPN
  network: xhttp
  port: 8443
  reality-opts:
    public-key: 167UuK8Oaxr23FtoB2a2UbzMRrdRyoHv8JeiIbt3yH4
    short-id: ''
  server: 159.194.226.13
  servername: ya.ru
  tls: true
  type: vless
  uuid: b6c29ae7-4748-4049-b642-b695c0d2c776
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_RUSSIA]
  proxies:
  - 🇷🇺 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_RUSSIA]
socks-port: 7891
