allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 32833
  reality-opts:
    public-key: PaTDdYBrlh1xBixdI0igvRRkf0vnUwMRzi-4oDyfS20
    short-id: a0a305ccc8e94aa8
  server: 172.238.232.239
  servername: www.intel.com
  tls: true
  type: vless
  uuid: 167ed405-7de9-4bff-b1ea-6e3d49c76b0b
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_ITALY]
  proxies:
  - 🇮🇹 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_ITALY]
socks-port: 7891
