allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🇹🇷 Gh0st #75'
  network: tcp
  port: 443
  reality-opts:
    public-key: rNBFVzV18kAj_ei4AqsgZywzmvD36WK9hcRdVnpHPAM
    short-id: c0573c8280a0c019
  server: 91.124.63.229
  servername: www.ya.ru
  tls: true
  type: vless
  uuid: acc50200-7f21-4f90-9cca-0057efcbf042
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_TÜRKIYE]
  proxies:
  - '🇹🇷 Gh0st #75'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_TÜRKIYE]
socks-port: 7891
