allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 40800
  reality-opts:
    public-key: zohUbvPLKVBwzuDmZNsaXXFYZSKA9_xEhdUyURChrgo
    short-id: 186e4c2732d61a3d
  server: 104.199.219.172
  servername: www.intel.com
  tls: true
  type: vless
  uuid: 5859f6a7-cda1-47c2-8353-fcdee281f31d
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_TAIWAN]
  proxies:
  - 🇹🇼 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_TAIWAN]
socks-port: 7891
