allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: xhttp
  port: 443
  reality-opts: {}
  server: 104.18.32.47
  servername: rus.aba-hum.store
  tls: true
  type: vless
  uuid: a5a544bf-e4b3-4651-9ff4-de3461910d87
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNKNOWN]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNKNOWN]
socks-port: 7891
