allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇧🇷 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 201.24.49.77
  servername: 201.24.49.77
  tls: false
  type: vless
  uuid: af60d475-3c13-41cf-af0e-18353d08877a
  ws-opts:
    path: /v1
- name: 🇧🇷 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 201.24.49.120
  servername: 201.24.49.120
  tls: false
  type: vless
  uuid: b671573f-6303-4cdf-ad50-0401d07e85bf
  ws-opts:
    path: /v1
- name: 🇧🇷 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.24.49.240
  servername: 201.24.49.240
  tls: false
  type: vless
  uuid: aa7d939b-feaa-4ad3-9615-74216f490807
  ws-opts:
    path: /v1
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_BRAZIL]
  proxies:
  - 🇧🇷 GhostVPN
  - 🇧🇷 GhostVPN
  - 🇧🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_BRAZIL]
socks-port: 7891
