allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇸🇪 GhostVPN
  network: xhttp
  port: 4443
  reality-opts:
    public-key: 9hX9xn4aKrsXXqWi9nLyuDm2izZ_klzFffTR8192Rxs
    short-id: ca9273f1a19a886e
  server: 177.3.215.41
  servername: idontknow.whit3.net
  tls: true
  type: vless
  uuid: 9b212e1c-9750-4dac-ae63-e6c537352dcb
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_SWEDEN]
  proxies:
  - 🇸🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_SWEDEN]
socks-port: 7891
