allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: VrBVCP2ZeR-D41K9BmaAiMyzWHUAj2N2uHLGVpJv3z0
    short-id: c72a5c4a1022f3c9
  server: 45.151.74.209
  servername: dl.google.com
  tls: true
  type: vless
  uuid: c7ae1368-b6ca-4d11-beef-bb76f68d1b80
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_GERMANY]
  proxies:
  - 🇩🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_GERMANY]
socks-port: 7891
