allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: 🇬🇧 GhostVPN
  password: MGU4ZjVkMGNhY2Y3YzM0NmIxMDgyNDQ5OGVjZjY2Y2Y=
  port: 61312
  server: 129.151.74.38
  type: ss
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o
    short-id: fdda9806fe5d8584
  server: 185.232.117.117
  servername: vl07.skorostnet.space
  tls: true
  type: vless
  uuid: c04bf2df-2b7f-44da-a893-3792d3910fd8
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
  proxies:
  - 🇬🇧 GhostVPN
  - 🇬🇧 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_UNITED_KINGDOM]
socks-port: 7891
