allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🇯🇵 GhostVPN
  network: tcp
  port: 55216
  server: 155.248.176.44
  servername: 155.248.176.44
  tls: false
  type: vmess
  uuid: 154dbc39-0921-cf11-29bd-156c5000d763
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_JAPAN]
  proxies:
  - 🇯🇵 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_JAPAN]
socks-port: 7891
