allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🏳️ Gh0st #57'
  network: tcp
  port: 62145
  reality-opts: {}
  server: 157.137.228.255
  servername: 157.137.228.255
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- cipher: aes-256-gcm
  name: '🏳️ Gh0st #63'
  password: TEzjfAYq2IjtuoS
  port: 6697
  server: 154.223.16.96
  type: ss
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_COLOMBIA]
  proxies:
  - '🏳️ Gh0st #57'
  - '🏳️ Gh0st #63'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_COLOMBIA]
socks-port: 7891
