allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 150.241.121.21
  servername: cloud445772.mvp-rk.site
  tls: true
  type: vless
  uuid: 83448201-7493-41df-8be1-4310bd161cfb
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [COUNTRY_CZECHIA]
  proxies:
  - 🏳️ GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [COUNTRY_CZECHIA]
socks-port: 7891
