allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇳🇱 GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 158.178.147.174
  servername: 158.178.147.174
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 83.147.246.153
  servername: 83.147.246.153
  tls: false
  type: vless
  uuid: 85223e1a-f55d-4d0d-b27d-39e8be49d220
  ws-opts:
    path: /v1
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 51125
  reality-opts: {}
  server: 45.77.53.179
  servername: 45.77.53.179
  tls: false
  type: vless
  uuid: b0f95fa6-2cc5-4e41-a33f-0b0ad58daaed
  ws-opts: {}
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 51815
  reality-opts: {}
  server: 91.107.242.197
  servername: 91.107.242.197
  tls: false
  type: vless
  uuid: f7e8a87f-e472-4fca-a393-fb9cc5b5dfa9
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: tcp
  port: 1301
  reality-opts: {}
  server: 46.149.67.4
  servername: 46.149.67.4
  tls: false
  type: vless
  uuid: 470a883b-da25-4f1c-92ed-6b3bb28cd182
  ws-opts: {}
- name: 🇩🇪 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 91.107.154.19
  servername: 91.107.154.19
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇳🇱 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 51.15.57.139
  servername: 51.15.57.139
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇳🇱 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 51.15.56.211
  servername: 51.15.56.211
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇩🇪 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 91.107.190.175
  servername: 91.107.190.175
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.79
  servername: 40.160.68.79
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed=2048
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.69.180
  servername: 40.160.69.180
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed=2048
- cipher: chacha20-ietf-poly1305
  name: 🇭🇰 GhostVPN
  password: ljqdalu13..
  port: 8313
  server: 95.40.120.162
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇷🇺 GhostVPN
  password: qIpg3esvBo9BBf3zRQ5_1Q
  port: 831
  server: 213.171.15.179
  type: ss
- alterId: 0
  cipher: auto
  name: 🇯🇵 GhostVPN
  network: tcp
  port: 55216
  server: 155.248.176.44
  servername: 155.248.176.44
  tls: false
  type: vmess
  uuid: 154dbc39-0921-cf11-29bd-156c5000d763
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: 🇹🇼 GhostVPN
  network: tcp
  port: 35034
  server: 165.154.195.38
  servername: 165.154.195.38
  tls: false
  type: vmess
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [MIXED_100]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇭🇰 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇯🇵 GhostVPN
  - 🇹🇼 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [MIXED_100]
socks-port: 7891
