allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇳🇱 GhostVPN
  network: grpc
  port: 443
  reality-opts: {}
  server: 78.17.132.147
  servername: 78.17.132.147
  tls: false
  type: vless
  uuid: 63ffaa18-d7dd-4bef-9479-9a979858850b
  ws-opts: {}
- name: 🇳🇱 GhostVPN
  network: grpc
  port: 443
  reality-opts: {}
  server: 78.17.132.148
  servername: 78.17.132.148
  tls: false
  type: vless
  uuid: 63ffaa18-d7dd-4bef-9479-9a979858850b
  ws-opts: {}
- name: 🇵🇱 GhostVPN
  network: grpc
  port: 443
  reality-opts: {}
  server: 31.56.188.183
  servername: 31.56.188.183
  tls: false
  type: vless
  uuid: 63ffaa18-d7dd-4bef-9479-9a979858850b
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 194.26.229.220
  servername: 194.26.229.220
  tls: false
  type: vless
  uuid: 47947923-49ac-49f8-86ed-2912bcbf2d18
  ws-opts:
    path: /v1
- name: 🇩🇪 GhostVPN
  network: grpc
  port: 443
  reality-opts: {}
  server: 78.17.147.128
  servername: 78.17.147.128
  tls: false
  type: vless
  uuid: 63ffaa18-d7dd-4bef-9479-9a979858850b
  ws-opts: {}
- name: 🇳🇱 GhostVPN
  network: grpc
  port: 443
  reality-opts: {}
  server: 94.156.131.91
  servername: 94.156.131.91
  tls: false
  type: vless
  uuid: 63ffaa18-d7dd-4bef-9479-9a979858850b
  ws-opts: {}
- cipher: chacha20-ietf-poly1305
  name: 🇳🇱 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 8080
  server: 193.29.139.225
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇬🇧 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 443
  server: 82.38.31.149
  type: ss
- name: 🏳️ GhostVPN
  network: xhttp
  port: 443
  reality-opts: {}
  server: 185.136.12.179
  servername: deu683.lackerdeu.org
  tls: true
  type: vless
  uuid: 2cca8201-c93e-40eb-bd8a-fea4170c169e
  ws-opts: {}
- cipher: chacha20-ietf-poly1305
  name: 🇬🇧 GhostVPN
  password: k1dBOmOB4oqi7Ump37a1bQ
  port: 8080
  server: 82.38.31.200
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇳🇱 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 443
  server: 193.29.139.225
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇳🇱 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 443
  server: 193.29.139.230
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇳🇱 GhostVPN
  password: 4a2rfixophdjffa8KVA4Aa
  port: 8080
  server: 193.29.139.234
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇳🇱 GhostVPN
  password: k1dBOmOB4oqi7Ump37a1bQ
  port: 8080
  server: 193.29.139.223
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇬🇧 GhostVPN
  password: zz0dHjDfoaSaZuRFLGH-hNfBALSEJUYD
  port: 1234
  server: 194.164.92.198
  type: ss
- name: 🇳🇱 GhostVPN
  network: xhttp
  port: 443
  reality-opts: {}
  server: 185.229.190.148
  servername: moein-bf821.b-cdn.net
  tls: true
  type: vless
  uuid: 311cadaf-79ed-4f84-be27-bcf46f920b41
  ws-opts: {}
- name: 🏳️ GhostVPN
  password: UO36402987
  port: 443
  server: 34.251.228.118
  skip-cert-verify: true
  sni: definite-ladybird.rooster465.autos
  type: trojan
- name: 🇸🇪 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 95.85.246.160
  servername: pl10.fast-connect-service.site
  tls: true
  type: vless
  uuid: '8033102198'
  ws-opts: {}
- name: 🇹🇷 GhostVPN
  network: xhttp
  port: 8088
  reality-opts:
    public-key: hYLvEGoxIMNpQkqxVJt298bBGE1Tz8dhtXGsPsLznj0
    short-id: 2acf8977eb67ea0c
  server: 158.94.216.232
  servername: www.yahoo.com
  tls: true
  type: vless
  uuid: de9f46e2-5785-4978-b1d0-c6b308a66b35
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.24.120.68
  servername: 201.24.120.68
  tls: false
  type: vless
  uuid: 59525c39-e731-4c27-bc9e-6d8cef67572c
  ws-opts:
    path: /v1
- cipher: chacha20-poly1305
  name: 🇬🇧 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 8080
  server: 82.38.31.46
  type: ss
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8020
  reality-opts: {}
  server: 216.106.183.132
  servername: 216.106.183.132
  tls: false
  type: vless
  uuid: aa8250e1-954c-449e-98fc-aa56a973a3f1
  ws-opts:
    path: /upload?ed=2560
- name: 🇫🇷 GhostVPN
  password: ND91608427
  port: 443
  server: 15.237.137.197
  skip-cert-verify: true
  sni: fancy-skink.rooster465.autos
  type: trojan
- alterId: 0
  cipher: auto
  name: 🇺🇸 GhostVPN
  network: tcp
  port: 443
  server: 165.140.216.142
  servername: 165.140.216.142
  tls: false
  type: vmess
  uuid: b65a2d69-5634-42a2-e4be-54e8a6176900
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.72
  servername: 40.160.68.72
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.118
  servername: 40.160.68.118
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed
- alterId: 0
  cipher: auto
  name: 🇺🇸 GhostVPN
  network: ws
  port: 2054
  server: 132.145.200.43
  servername: 132.145.200.43
  tls: false
  type: vmess
  uuid: ceeaee0b-89af-40b1-aa14-577cbde03a89
  ws-opts:
    headers:
      Host: ''
    path: /p
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.55
  servername: 40.160.68.55
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.136
  servername: 40.160.68.136
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.69.97
  servername: 40.160.69.97
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.69.53
  servername: 40.160.69.53
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: ''
- name: 🇺🇸 GhostVPN
  network: ws
  port: 8080
  reality-opts: {}
  server: 40.160.68.126
  servername: 40.160.68.126
  tls: false
  type: vless
  uuid: 11af1c47-865a-47c6-92ff-118013655d78
  ws-opts:
    path: /?ed
- name: 🏳️ GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 158.247.125.162
  servername: 158.247.125.162
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: 🇺🇸 GhostVPN
  network: ws
  port: 39495
  server: 129.146.77.248
  servername: 129.146.77.248
  tls: false
  type: vmess
  uuid: f836c736-87fc-4fde-aabc-00857ecdff3e
  ws-opts:
    headers:
      Host: ''
    path: /cctv13.m3u8
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 44.244.3.114
  skip-cert-verify: true
  sni: pet-ghost.rooster465.autos
  type: trojan
- alterId: 0
  cipher: auto
  name: 🇹🇼 GhostVPN
  network: tcp
  port: 35034
  server: 165.154.195.38
  servername: 165.154.195.38
  tls: false
  type: vmess
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 44.242.235.129
  skip-cert-verify: true
  sni: devoted-tapir.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [MIXED_100]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇬🇧 GhostVPN
  - 🏳️ GhostVPN
  - 🇬🇧 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇳🇱 GhostVPN
  - 🏳️ GhostVPN
  - 🇸🇪 GhostVPN
  - 🇹🇷 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇫🇷 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🏳️ GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇹🇼 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [MIXED_100]
socks-port: 7891
