allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇷🇺 GhostVPN
  network: tcp
  port: 28473
  reality-opts: {}
  server: 78.159.245.32
  servername: secure.furrycdn.net
  tls: true
  type: vless
  uuid: 93bfd314-a270-447f-86f4-cf4fc5b2f3ff
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: JwL5KoiWkCJI2vMJxyTEplfv-zBAtwxOH8SMbw6QHzY
    short-id: cd40c992fe4b10c2
  server: 46.246.92.109
  servername: www.rumedia-cdn.com
  tls: true
  type: vless
  uuid: 14f19724-de91-4285-a633-aa8e2caaf812
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  password: 0ebb269c9f2d4e8e46b0cd4105a55134
  port: 49361
  server: 163.245.196.68
  skip-cert-verify: true
  sni: 163.245.196.68.sslip.io
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [MIXED_100]
  proxies:
  - 🇷🇺 GhostVPN
  - 🇸🇪 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [MIXED_100]
socks-port: 7891
