allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: '🇮🇳 Gh0st #71'
  password: WOir3lXBhMHDcLFPQdEZXPu37_pTQDCXfm
  port: 28061
  server: 103.111.114.55
  type: ss
- cipher: chacha20-ietf-poly1305
  name: '🇮🇳 Gh0st #89'
  password: WOir3lXBhMHDcLFPQdEZXPu37_pTQDCXfm
  port: 28061
  server: 103.111.114.71
  type: ss
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_SS]
  proxies:
  - '🇮🇳 Gh0st #71'
  - '🇮🇳 Gh0st #89'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_SS]
socks-port: 7891
