allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇮 GhostVPN
  network: tcp
  port: 39633
  reality-opts: {}
  server: 65.109.215.50
  servername: 65.109.215.50
  tls: false
  type: vless
  uuid: de5b01f7-0697-49ec-aeb1-6ef0361344fb
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  network: xhttp
  port: 4443
  reality-opts:
    public-key: 9hX9xn4aKrsXXqWi9nLyuDm2izZ_klzFffTR8192Rxs
    short-id: ca9273f1a19a886e
  server: 177.3.215.41
  servername: idontknow.whit3.net
  tls: true
  type: vless
  uuid: 9b212e1c-9750-4dac-ae63-e6c537352dcb
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.24.51.241
  servername: 201.24.51.241
  tls: false
  type: vless
  uuid: 5181e3af-4a0c-47d7-8beb-7e4fa4786cdd
  ws-opts:
    path: /v1
- name: 🇷🇺 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.34.137.15
  servername: 201.34.137.15
  tls: false
  type: vless
  uuid: 716903b1-e6bf-4420-9e27-65e4451692e9
  ws-opts:
    path: /v1
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 23147
  reality-opts:
    public-key: Q5olKgn1QNzByW6thPsIA-svXqdzSgyVOSsF9GiTvXI
    short-id: 5f5d4386c2c53c
  server: 104.105.18.183
  servername: www.amd.com
  tls: true
  type: vless
  uuid: 2cf1f3f4-f949-495f-95d6-7f3f6675c13f
  ws-opts: {}
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 32396
  reality-opts:
    public-key: Pj1XWo01sxdH8jKJ_8DoJiZDFANHFKRAqOncP8RNkwU
    short-id: dd6ce6af95001a
  server: 172.232.196.241
  servername: www.sony.com
  tls: true
  type: vless
  uuid: bd6ebd72-25cd-4209-a418-a8c72946da90
  ws-opts: {}
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: em5MbaJeZoe--syIy7L8MEoNBwN1mLB2ur_YAY8PuQ0
    short-id: daf012feff3b00d0
  server: 2.24.131.46
  servername: www.cloudflare.com
  tls: true
  type: vless
  uuid: 5e127068-e5d0-4c3f-86c4-dfb6b34e64a4
  ws-opts: {}
- name: 🇮🇳 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: Gy6W0bXf2bpxoG1k3szp8X0ekzoyXlEtzT8V4mYQ3EE
    short-id: 29fe4205ddc971a8
  server: 194.61.31.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 0bf89828-484f-4710-9581-12aa961e3bf1
  ws-opts: {}
- name: 🇸🇬 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: yVb3JqVqlnXhiIb3E-gAVvgsXCpWgoeLIAJau9yuZ1I
    short-id: 3fc9b11ceeb2cc6b
  server: 217.217.254.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 30430ca4-9a16-4689-a276-4014599d2f39
  ws-opts: {}
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 30837
  reality-opts:
    public-key: LXPNhrAGxr_QE4YCdJfKE40ebsPNIHnLbydhl6bipCo
    short-id: 97101ba788915e5a
  server: 35.201.163.218
  servername: www.sony.com
  tls: true
  type: vless
  uuid: 85a6bd94-83a9-4e80-849f-c06d7011d1a4
  ws-opts: {}
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 21776
  reality-opts:
    public-key: nm6jFiI7_auZ15UMqpeEbiITrK4OR2rfFTqXhe5pMFA
    short-id: 79b6f82800c68925
  server: 34.80.164.239
  servername: www.tesla.com
  tls: true
  type: vless
  uuid: b0399730-1618-4727-8ddd-2baf94ab90d6
  ws-opts: {}
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 34376
  reality-opts:
    public-key: Atq4Fo_Mg48QtKXagBW9jnhaQSDUCiKgnATB2EU6OHU
    short-id: 8dbafb690450d8a9
  server: 34.81.129.171
  servername: www.sony.com
  tls: true
  type: vless
  uuid: bf8cc771-51a0-4395-810f-1f135325cfc1
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 200.165.234.119
  servername: 200.165.234.119
  tls: false
  type: vless
  uuid: 936b7663-a841-4b42-b639-6e3fab1dbf45
  ws-opts:
    path: /v1
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 35412
  reality-opts:
    public-key: eg6DfbLnWtz7PubkXRYvSuQx6QWIRxUsn4l7QEO3Cg4
    short-id: 0630b874d595
  server: 35.229.136.113
  servername: www.amd.com
  tls: true
  type: vless
  uuid: 5d3cbdb2-b82d-4078-82b8-5dd413cca82b
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_VLESS]
  proxies:
  - 🇫🇮 GhostVPN
  - 🇸🇪 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇮🇹 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇮🇳 GhostVPN
  - 🇸🇬 GhostVPN
  - 🇹🇼 GhostVPN
  - 🇹🇼 GhostVPN
  - 🇹🇼 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇹🇼 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_VLESS]
socks-port: 7891
