allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇨🇭 GhostVPN
  password: y3b03zx3tznhyo538p4c
  port: 53261
  server: 86.106.84.195
  skip-cert-verify: true
  sni: speedtest.tinkoff.ru
  type: trojan
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 44.244.3.114
  skip-cert-verify: true
  sni: pet-ghost.rooster465.autos
  type: trojan
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 44.242.235.129
  skip-cert-verify: true
  sni: devoted-tapir.rooster465.autos
  type: trojan
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 35.91.251.124
  skip-cert-verify: true
  sni: sincere-gelding.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_TROJAN]
  proxies:
  - 🇨🇭 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_TROJAN]
socks-port: 7891
