allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🇪🇸 Gh0st #47'
  password: 2eutknankxtbgkwcajzt
  port: 52794
  server: 193.148.19.210
  skip-cert-verify: true
  sni: www.vk.com
  type: trojan
- name: '🇭🇰 Gh0st #64'
  password: d1960ba9f0f6353353994fa844cf817b
  port: 6357
  server: 18.163.180.201
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: '🇸🇬 Gh0st #66'
  password: pvZE3UfT0ziK1omVLlsjINBqeqqwab1M
  port: 50573
  server: 139.59.238.97
  skip-cert-verify: true
  sni: 139.59.238.97
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_TROJAN]
  proxies:
  - '🇪🇸 Gh0st #47'
  - '🇭🇰 Gh0st #64'
  - '🇸🇬 Gh0st #66'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_TROJAN]
socks-port: 7891
