allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇬🇧 GhostVPN
  password: HKSvOU0Ruej4DuNgM41S+dNISlcFU45tqwqj3BQCuYY=
  port: 61312
  server: 129.151.84.127
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇭🇰 GhostVPN
  password: ljqdalu13..
  port: 8313
  server: 95.40.120.162
  type: ss
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_SS]
  proxies:
  - 🇬🇧 GhostVPN
  - 🇭🇰 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_SS]
socks-port: 7891
