allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇷🇺 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 194.26.229.157
  servername: 194.26.229.157
  tls: false
  type: vless
  uuid: c05888f0-4029-45c8-bea7-ea5eff564462
  ws-opts:
    path: /v1
- name: 🇧🇷 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 201.24.49.237
  servername: 201.24.49.237
  tls: false
  type: vless
  uuid: af412668-578c-4296-bc8c-8fac6a8d9003
  ws-opts:
    path: /v1
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 186.190.211.188
  servername: 186.190.211.188
  tls: true
  type: vless
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 443
  reality-opts: {}
  server: 31.76.88.10
  servername: cf5.rumedia-cdn.com
  tls: true
  type: vless
  uuid: 03c48eca-e0aa-4e18-998c-1f53f1de293c
  ws-opts:
    path: /cdn/v3/live
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 32396
  reality-opts:
    public-key: Pj1XWo01sxdH8jKJ_8DoJiZDFANHFKRAqOncP8RNkwU
    short-id: dd6ce6af95001a
  server: 172.232.196.241
  servername: www.sony.com
  tls: true
  type: vless
  uuid: bd6ebd72-25cd-4209-a418-a8c72946da90
  ws-opts: {}
- name: 🇷🇺 GhostVPN
  network: ws
  port: 443
  reality-opts: {}
  server: 147.45.229.3
  servername: gaaga.korgivps.ru
  tls: true
  type: vless
  uuid: 338efc17-02d7-433b-902a-e7d4771dc802
  ws-opts:
    path: /api/user
- name: 🏳️ GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: 6HRVYg1i4ah9VhuV5hne2-JA8Z5HTV5jbFi-h3qKsDQ
    short-id: dd4d615422c6424c
  server: 109.104.106.135
  servername: d2-ro.cloud-cdn.xyz
  tls: true
  type: vless
  uuid: 36a9a243-84aa-4bbf-8a1d-fc4739795d46
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: tcp
  port: 15443
  reality-opts:
    public-key: cpoZcpYNYSvFXGGB21tByHUoNd7-FYrJ0UP7ZDfSFCs
    short-id: a1b2c3d4
  server: 31.77.220.163
  servername: max.ru
  tls: true
  type: vless
  uuid: 1206bad5-dcc9-410e-9595-d9fe9ee54085
  ws-opts: {}
- name: 🇮🇳 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: Gy6W0bXf2bpxoG1k3szp8X0ekzoyXlEtzT8V4mYQ3EE
    short-id: 29fe4205ddc971a8
  server: 194.61.31.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 0bf89828-484f-4710-9581-12aa961e3bf1
  ws-opts: {}
- name: 🇹🇼 GhostVPN
  network: tcp
  port: 40800
  reality-opts:
    public-key: zohUbvPLKVBwzuDmZNsaXXFYZSKA9_xEhdUyURChrgo
    short-id: 186e4c2732d61a3d
  server: 104.199.219.172
  servername: www.intel.com
  tls: true
  type: vless
  uuid: 5859f6a7-cda1-47c2-8353-fcdee281f31d
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_VLESS]
  proxies:
  - 🇷🇺 GhostVPN
  - 🇧🇷 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇮🇹 GhostVPN
  - 🇷🇺 GhostVPN
  - 🏳️ GhostVPN
  - 🇺🇸 GhostVPN
  - 🇮🇳 GhostVPN
  - 🇹🇼 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_VLESS]
socks-port: 7891
