allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 186.190.211.188
  servername: 186.190.211.188
  tls: true
  type: vless
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 57878
  reality-opts: {}
  server: 38.246.226.240
  servername: 38.246.226.240
  tls: false
  type: vless
  uuid: 535f0e03-24d4-4268-ac40-5af829e8e59b
  ws-opts:
    path: /535f0e03
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_VLESS]
  proxies:
  - 🇬🇧 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_VLESS]
socks-port: 7891
