allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  password: UO36402987
  port: 443
  server: 34.251.228.118
  skip-cert-verify: true
  sni: definite-ladybird.rooster465.autos
  type: trojan
- name: 🇫🇷 GhostVPN
  password: QV31589740
  port: 443
  server: 51.44.160.58
  skip-cert-verify: true
  sni: great-krill.rooster465.autos
  type: trojan
- name: 🏳️ GhostVPN
  password: bptHV5U91mWneB61rRKhCQ8f
  port: 443
  server: 87.121.218.169
  skip-cert-verify: true
  sni: 87.121.218.169
  type: trojan
- name: 🇺🇸 GhostVPN
  password: ND91608427
  port: 443
  server: 44.244.3.114
  skip-cert-verify: true
  sni: pet-ghost.rooster465.autos
  type: trojan
- name: 🇸🇬 GhostVPN
  password: FH72359861
  port: 443
  server: 54.254.235.88
  skip-cert-verify: true
  sni: charming-ox.rooster465.autos
  type: trojan
- name: 🇯🇵 GhostVPN
  password: FH72359861
  port: 443
  server: 52.196.34.5
  skip-cert-verify: true
  sni: welcome-owl.rooster465.autos
  type: trojan
- name: 🇯🇵 GhostVPN
  password: ND91608427
  port: 443
  server: 18.181.164.216
  skip-cert-verify: true
  sni: upright-impala.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_TROJAN]
  proxies:
  - 🏳️ GhostVPN
  - 🇫🇷 GhostVPN
  - 🏳️ GhostVPN
  - 🇺🇸 GhostVPN
  - 🇸🇬 GhostVPN
  - 🇯🇵 GhostVPN
  - 🇯🇵 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_TROJAN]
socks-port: 7891
