allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: 🇳🇱 GhostVPN
  network: tcp
  port: 30011
  server: 23.137.249.110
  servername: 23.137.249.110
  tls: true
  type: vmess
  uuid: a7aee69e-6e02-47d1-8172-701866bbb28c
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: 🇩🇪 GhostVPN
  network: ws
  port: 46945
  server: 189.24.106.165
  servername: 189.24.106.165
  tls: false
  type: vmess
  uuid: 7aa3a024-e333-4b63-99a2-3db9d3b2054e
  ws-opts:
    headers:
      Host: gw.alicdn.com
    path: /
- alterId: 0
  cipher: auto
  name: 🇮🇷 GhostVPN
  network: ws
  port: 443
  server: 185.59.113.4
  servername: 185.59.113.4
  tls: false
  type: vmess
  uuid: efc02ac5-685e-4c88-b3da-ce3dfc236585
  ws-opts:
    headers:
      Host: amir.amirport.ir
    path: /
- alterId: 0
  cipher: auto
  name: 🇦🇪 GhostVPN
  network: tcp
  port: 1233
  server: 195.133.192.232
  servername: gb.uniquenames.net
  tls: true
  type: vmess
  uuid: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_VMESS]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇮🇷 GhostVPN
  - 🇦🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_VMESS]
socks-port: 7891
