allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇳🇱 GhostVPN
  password: Bq7fNTetsKxZR/aGO54gR4+Dac67uZ+YYRnIWuHGIo4=
  port: 45819
  server: 141.148.237.51
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇳🇱 GhostVPN
  password: 7vDcApvjEM/BKjaxYQLBjym80MGCi6eJ8jkfoY+6bUs=
  port: 45819
  server: 141.148.239.62
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇳🇱 GhostVPN
  password: 14zduVOpqZOK6iayk+xd34h98ymp6qr2NuJj2xtWXiY=
  port: 45819
  server: 158.178.155.37
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇩🇪 GhostVPN
  password: IFvwvrqx26KIutn01x+IDo6chyktXgr2b0UvXNliBzc=
  port: 59924
  server: 141.147.53.115
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇩🇪 GhostVPN
  password: +gebuWwfimHcw5FvH6Sfnw3ppf05PeV2M8QPMsr38oY=
  port: 59924
  server: 129.159.10.51
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇩🇪 GhostVPN
  password: kmkoVYMV3CiplXx9HrZ9swEnhpwqXMY0rOXC34dEi08=
  port: 59924
  server: 130.61.144.2
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇳🇱 GhostVPN
  password: HRqwosfXqmllcha4w+K3LxYB8vJ+L1qRJwBZgVE1kRY=
  port: 45819
  server: 84.235.171.56
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 🇬🇧 GhostVPN
  password: oZIoA69Q8yhcQV8ka3Pa3A
  port: 8080
  server: 82.38.31.7
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇬🇧 GhostVPN
  password: EfGEytWYCn3S7KiNjCTKlsDjG4MdZzAB+GTSuKlREUQ=
  port: 61312
  server: 134.65.59.103
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇬🇧 GhostVPN
  password: m8FfNqhzuXPMFe0gaunpieW87PteuaBFonYmUgPM+tg=
  port: 61312
  server: 129.151.80.142
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇺🇸 GhostVPN
  password: 3RVXu5xARCPQlD3Fv/cmQt7o/XGqUZLwrTTt0FkA2vo=
  port: 50356
  server: 129.146.62.211
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇺🇸 GhostVPN
  password: eR3ZjLaKtCr4U1m81fqUrBHGvIuRkm64vt0kSZDgIGQ=
  port: 50356
  server: 129.146.76.20
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇺🇸 GhostVPN
  password: RoFdephcuY8+LrAoVBBy0QjUxywV5XKPrjU2sc0RtKw=
  port: 50356
  server: 129.146.73.67
  type: ss
- cipher: 2022-blake3-chacha20-poly1305
  name: 🇺🇸 GhostVPN
  password: xDEXXhNhDE1+LUHo1bMUnTwFqgPX3i7cpDX+hUx+dRg=
  port: 50356
  server: 129.146.60.116
  type: ss
- cipher: aes-256-gcm
  name: 🇯🇵 GhostVPN
  password: 3eOFeNssde7PYYMv
  port: 80
  server: 84.247.155.196
  type: ss
proxy-groups:
- name: Free_VPN_Aggregator [PROTO_SS]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇳🇱 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇯🇵 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [PROTO_SS]
socks-port: 7891
