allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: '🇫🇷 Gh0st #22'
  password: IQ68037294
  port: 443
  server: 35.180.10.212
  skip-cert-verify: true
  sni: firm-warthog.rooster465.autos
  type: trojan
- name: '🇫🇷 Gh0st #29'
  password: WG39087154
  port: 443
  server: 35.181.168.168
  skip-cert-verify: true
  sni: nearby-cod.rooster465.autos
  type: trojan
- name: '🇫🇷 Gh0st #30'
  password: PD07395842
  port: 443
  server: 13.39.195.215
  skip-cert-verify: true
  sni: tough-pigeon.rooster465.autos
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [RECOMMENDED]
  proxies:
  - '🇫🇷 Gh0st #22'
  - '🇫🇷 Gh0st #29'
  - '🇫🇷 Gh0st #30'
  type: select
rules:
- MATCH,Free_VPN_Aggregator [RECOMMENDED]
socks-port: 7891
