allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 5443
  reality-opts: {}
  server: 194.31.223.87
  servername: de.wlrus.cfd
  tls: true
  type: vless
  uuid: d71aecee-ef16-418e-baf5-2b2458122d5a
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [TOP_50_FAST]
  proxies:
  - 🇩🇪 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [TOP_50_FAST]
socks-port: 7891
