allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇳🇱 GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 158.178.150.159
  servername: 158.178.150.159
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- cipher: chacha20-ietf-poly1305
  name: 🇭🇰 GhostVPN
  password: ljqdalu13..
  port: 8313
  server: 95.40.120.162
  type: ss
- name: 🇺🇸 GhostVPN
  password: r49gssuondznyu2eex83
  port: 50740
  server: 14.1.28.76
  skip-cert-verify: true
  sni: 14.1.28.76
  type: trojan
proxy-groups:
- name: Free_VPN_Aggregator [TOP_30_FAST]
  proxies:
  - 🇳🇱 GhostVPN
  - 🇭🇰 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [TOP_30_FAST]
socks-port: 7891
