allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🏳️ GhostVPN
  network: grpc
  port: 443
  reality-opts:
    public-key: uE1WBdW9se1rQnx8Vh-a1jjaehzK-iUmCVrPui5KU3g
    short-id: 53499a662395
  server: 87.120.196.135
  servername: ai.android
  tls: true
  type: vless
  uuid: 860c29ef-ea15-4fa7-aa2e-249dcbb64c79
  ws-opts: {}
- name: 🇳🇱 GhostVPN
  network: tcp
  port: 62145
  reality-opts: {}
  server: 144.21.43.130
  servername: 144.21.43.130
  tls: false
  type: vless
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  ws-opts: {}
- name: 🏳️ GhostVPN
  network: ws
  port: 11443
  reality-opts: {}
  server: 89.125.13.3
  servername: nlhis.bkvpn.online
  tls: true
  type: vless
  uuid: 3fd3bab8-f0fc-4ac0-b209-4a5b636a8643
  ws-opts:
    path: /ws-ee
- name: 🇵🇱 GhostVPN
  password: 9pCELV5d3T5FUf4-5KWkeALzv-owtSVD
  port: 9443
  server: 31.77.56.107
  skip-cert-verify: true
  sni: nlhis.bkvpn.online
  type: trojan
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 144.31.112.199
  servername: pl2.fast-connect-service.site
  tls: true
  type: vless
  uuid: '8033102198'
  ws-opts: {}
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 31.56.188.152
  servername: pl11.fast-connect-service.site
  tls: true
  type: vless
  uuid: '8033102198'
  ws-opts: {}
- name: 🇵🇱 GhostVPN
  network: ws
  port: 11443
  reality-opts: {}
  server: 31.77.56.107
  servername: nlhis.bkvpn.online
  tls: true
  type: vless
  uuid: 3fd3bab8-f0fc-4ac0-b209-4a5b636a8643
  ws-opts:
    path: /ws-pl
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 95.85.253.134
  servername: pl5.fast-connect-service.site
  tls: true
  type: vless
  uuid: '8033102198'
  ws-opts: {}
- name: 🇫🇷 GhostVPN
  password: QV31589740
  port: 443
  server: 51.44.160.58
  skip-cert-verify: true
  sni: great-krill.rooster465.autos
  type: trojan
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts: {}
  server: 82.26.91.87
  servername: faster.yandex-apicloud.ru
  tls: true
  type: vless
  uuid: 7e760d89-a8f4-4a87-8f10-b4af28c61b7f
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  password: 9pCELV5d3T5FUf4-5KWkeALzv-owtSVD
  port: 9443
  server: 144.31.230.95
  skip-cert-verify: true
  sni: nlhis.bkvpn.online
  type: trojan
- name: 🇦🇪 GhostVPN
  network: tcp
  port: 2083
  reality-opts: {}
  server: 89.36.137.206
  servername: edge-tr-ist.cdn.sx
  tls: true
  type: vless
  uuid: 7fa91a52-54d0-442f-b550-cf83d916918c
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  network: ws
  port: 11443
  reality-opts: {}
  server: 144.31.230.95
  servername: nlhis.bkvpn.online
  tls: true
  type: vless
  uuid: 3fd3bab8-f0fc-4ac0-b209-4a5b636a8643
  ws-opts:
    path: /ws-se2
- name: 🇹🇷 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: G_LkIUtwCR5RoHxB021-jY8DlwXwKKKgFOes8p54XU0
    short-id: 40c3a20ae97f78a0
  server: 45.136.5.49
  servername: turkey.anonch.net
  tls: true
  type: vless
  uuid: d16a7171-625d-4d09-9459-859f1c9b3b0a
  ws-opts: {}
- name: 🇫🇮 GhostVPN
  network: ws
  port: 11443
  reality-opts: {}
  server: 2.26.3.131
  servername: nlhis.bkvpn.online
  tls: true
  type: vless
  uuid: 3fd3bab8-f0fc-4ac0-b209-4a5b636a8643
  ws-opts:
    path: /ws-fi
- name: 🇵🇱 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: tszWkJf8EdAkXhxvD-T_xA08SjU_x7lf15lXrPCLVn8
    short-id: 3c88b649989ffa95
  server: 188.255.163.44
  servername: www.ya.ru
  tls: true
  type: vless
  uuid: acc50200-7f21-4f90-9cca-0057efcbf042
  ws-opts: {}
- name: 🇧🇷 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: yg6IqqBKuUew1C26U8I2ZiQuBXLcGSKN3MyxEzhsaFM
    short-id: b6ff5a25b94803d8
  server: 147.45.116.30
  servername: br-storage10.infrastucture.site
  tls: true
  type: vless
  uuid: eac6ea16-8963-4948-8ba8-0dd3bab4773e
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [TOP_30_FAST]
  proxies:
  - 🏳️ GhostVPN
  - 🇳🇱 GhostVPN
  - 🏳️ GhostVPN
  - 🇵🇱 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇫🇷 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇸🇪 GhostVPN
  - 🇦🇪 GhostVPN
  - 🇸🇪 GhostVPN
  - 🇹🇷 GhostVPN
  - 🇫🇮 GhostVPN
  - 🇵🇱 GhostVPN
  - 🇧🇷 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [TOP_30_FAST]
socks-port: 7891
