allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇫🇮 GhostVPN
  network: tcp
  port: 39633
  reality-opts: {}
  server: 65.109.215.50
  servername: 65.109.215.50
  tls: false
  type: vless
  uuid: de5b01f7-0697-49ec-aeb1-6ef0361344fb
  ws-opts: {}
- name: 🇸🇪 GhostVPN
  network: xhttp
  port: 4443
  reality-opts:
    public-key: 9hX9xn4aKrsXXqWi9nLyuDm2izZ_klzFffTR8192Rxs
    short-id: ca9273f1a19a886e
  server: 177.3.215.41
  servername: idontknow.whit3.net
  tls: true
  type: vless
  uuid: 9b212e1c-9750-4dac-ae63-e6c537352dcb
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.24.51.241
  servername: 201.24.51.241
  tls: false
  type: vless
  uuid: 5181e3af-4a0c-47d7-8beb-7e4fa4786cdd
  ws-opts:
    path: /v1
- name: 🇷🇺 GhostVPN
  network: ws
  port: 4100
  reality-opts: {}
  server: 201.34.137.15
  servername: 201.34.137.15
  tls: false
  type: vless
  uuid: 716903b1-e6bf-4420-9e27-65e4451692e9
  ws-opts:
    path: /v1
- name: 🇩🇪 GhostVPN
  network: tcp
  port: 23147
  reality-opts:
    public-key: Q5olKgn1QNzByW6thPsIA-svXqdzSgyVOSsF9GiTvXI
    short-id: 5f5d4386c2c53c
  server: 104.105.18.183
  servername: www.amd.com
  tls: true
  type: vless
  uuid: 2cf1f3f4-f949-495f-95d6-7f3f6675c13f
  ws-opts: {}
- name: 🇮🇹 GhostVPN
  network: tcp
  port: 32396
  reality-opts:
    public-key: Pj1XWo01sxdH8jKJ_8DoJiZDFANHFKRAqOncP8RNkwU
    short-id: dd6ce6af95001a
  server: 172.232.196.241
  servername: www.sony.com
  tls: true
  type: vless
  uuid: bd6ebd72-25cd-4209-a418-a8c72946da90
  ws-opts: {}
- name: 🇬🇧 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: em5MbaJeZoe--syIy7L8MEoNBwN1mLB2ur_YAY8PuQ0
    short-id: daf012feff3b00d0
  server: 2.24.131.46
  servername: www.cloudflare.com
  tls: true
  type: vless
  uuid: 5e127068-e5d0-4c3f-86c4-dfb6b34e64a4
  ws-opts: {}
- name: 🇮🇳 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: Gy6W0bXf2bpxoG1k3szp8X0ekzoyXlEtzT8V4mYQ3EE
    short-id: 29fe4205ddc971a8
  server: 194.61.31.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 0bf89828-484f-4710-9581-12aa961e3bf1
  ws-opts: {}
- name: 🇸🇬 GhostVPN
  network: tcp
  port: 2053
  reality-opts:
    public-key: yVb3JqVqlnXhiIb3E-gAVvgsXCpWgoeLIAJau9yuZ1I
    short-id: 3fc9b11ceeb2cc6b
  server: 217.217.254.126
  servername: www.apple.com
  tls: true
  type: vless
  uuid: 30430ca4-9a16-4689-a276-4014599d2f39
  ws-opts: {}
- name: 🇺🇸 GhostVPN
  network: ws
  port: 2200
  reality-opts: {}
  server: 200.165.234.119
  servername: 200.165.234.119
  tls: false
  type: vless
  uuid: 936b7663-a841-4b42-b639-6e3fab1dbf45
  ws-opts:
    path: /v1
proxy-groups:
- name: Free_VPN_Aggregator [TOP_50_FAST]
  proxies:
  - 🇫🇮 GhostVPN
  - 🇸🇪 GhostVPN
  - 🇺🇸 GhostVPN
  - 🇷🇺 GhostVPN
  - 🇩🇪 GhostVPN
  - 🇮🇹 GhostVPN
  - 🇬🇧 GhostVPN
  - 🇮🇳 GhostVPN
  - 🇸🇬 GhostVPN
  - 🇺🇸 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [TOP_50_FAST]
socks-port: 7891
