allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- name: 🇷🇺 GhostVPN
  network: tcp
  port: 443
  reality-opts:
    public-key: l0R5_L16z0BMq5HhYvA538EJd3ztzHgIOtysCl6Q60U
    short-id: e78c4073
  server: 213.226.112.113
  servername: rutube.ru
  tls: true
  type: vless
  uuid: a2738d8d-ed26-4b13-a4a2-b89c7238cd10
  ws-opts: {}
proxy-groups:
- name: Free_VPN_Aggregator [WL_50]
  proxies:
  - 🇷🇺 GhostVPN
  type: select
rules:
- MATCH,Free_VPN_Aggregator [WL_50]
socks-port: 7891
